### ISSUE TITLE
LEMP provisioning on the same machine

### ISSUE THREAD

**Issue by jonwhittlestone** [arbabnazar/ansible-roles#5]
Hi, rather than on another server, what would inventory and main,yml look like if I wanted to provision on the local/native OS?

I am on Ubuntu fwiw.

Thanks

**Comment by arbabnazar** [comment]
Your playbook should like like this, the most important parameter is `all`

``` yaml
---
- hosts: all
  become: yes
  gather_facts: yes
  roles:
    - LEMP
```

Then run this command:

```
ansible-playbook -i 'localhost,' -c local site.yml
```

Hope that will help you, please let me know, if you need any help.
Thanks
